safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    http://dilettant.se/thepublicoffice
# url: http://dilettant.github.com/thepublicoffice

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

gravasize: 142

about:
  - team
  - project_phases:
    - phase_I
    - phase_II
  - philosophy:
    - open_source
    - cooperation
    - commons
    - diversity
