# DEFAULTS
# ========

safe:        false
auto:        true
server:      false

# SITE VARS
# =========
title: The public office
subtitle: "At the swedish museum of architecture<br>30 oct - 30 nov, 2012"
description: "The Public Office is a long-term development project that seeks to articulate an idea of open and rent-free work and meeting places, where the public is given the opportunity to engage in work and further education. During several project phases, we explore the concept’s possibilities and potential functions in an increasingly mobile labor market, as well as in urban planning and local community development, business development and integration."
author: "http://dilettant.se"
copyright: "This site is open source and is proudly hosted on GitHub."

amuseettitle: The public office at the swedish museum of architecture
dates: "30 OCT - 30 NOV 2012"
times: "Tuesday-Saturday between 10.00-18.00"
join: "Join The public office at The swedish museum of architecture"
more: "Read more"
bannername: museumofarchitecture
baseurl:    http://thepublicoffice.se
assetsurl: http://allmannakontoret.se

prose: "http://prose.io/#dilettant/thepublicoffice/edit/gh-pages"
mainrepo : "_posts"
repo : "_posts/amuseet"
githubrepourl: "https://github.com/dilettant/thepublicoffice#the-public-office" 
flattrurl: "https://flattr.com/thing/945788/The-Public-Office"

lang: en
gravasize: 60

# MENUS
# =====

# MAIN
# -----
menu_main:
  - home
  - about
  - concept
  - contact

# ABOUT
# -----
menu_about:
  - team
  - philosophy:
    - Cooperation
    - Commons
    - Diversity
    - Open_Source
  - project_phases:
    - Phase_I
    - Phase_II
    - Phase_III

# CONCEPT
# ------
menu_concept:
  - summary
  - starting_points_and_perspectives:
    - Changes_in_the_labour_market
    - Public_meeting_places_and_the_right_to_work
    - Public_meeting_places_in_local_development
    - Work_health_and_environment
  - the_vision_of_the_public_office:
    - The_public_office_in_practice
    - User_groups
    - Ownership_forms_and_guidelines
    - Forms_of_funding
    - Form_and_content_of_the_activities
  - suggestions_for_forms_of_operation:
    - Establishment_of_the_public_office_as_a_new_institution
    - Use_of_temporarily_available_spaces
    - Expansion_of_the_mandate_of_existing_institutions
  - the_public_office_as_a_political_issue:
    - Labour
    - Culture
    - Business
    - Education


# DICTIONARY
# ==========
newsletter: Newsletter
support: Support us
connect: Follow us
swedish: Swedish
english: English
index: Home
welcome: Welcome
support: Support
connect: Connect
