# DEFAULTS
# ========

safe:        false
auto:        true
server:      false

# SITE VARS
# =========

title: The public office
subtitle: "At the swedish museum of architecture<br>30 oct - 30 nov, 2012"
times: "Tuesday-Saturday between 10.00-18.00"
amuseettitle: The public office at the swedish museum of architecture
# baseurl:    http://thepublicoffice.se
# assetsurl : http://allmannakontoret.se
baseurl:    http://thepublicoffice.se
assetsurl:    http://thepublicoffice.se

bannername: museumofarchitecture

prose: "http://prose.io/#dilettant/thepublicoffice/edit/gh-pages"
repo : "_posts/amuseet"
githubrepourl: "https://github.com/dilettant/thepublicoffice" 
flattrurl: "https://flattr.com/thing/945788/The-Public-Office"

lang: en
gravasize: 60

# MENUS
# =====

# MAIN
# -----
menu_main:
  - index
  - about
  - concept
  - contact

# ABOUT
# -----
menu_about:
  - team
  - philosophy:
    - cooperation
    - commons
    - diversity
    - open_source
  - project_phases:
    - phase_1
    - phase_2

# CONCEPT
# ------
menu_concept:
  - summary
  - starting_points_and_perspectives:
    - changes_in_the_labour_market
    - public_meeting_places_and_the_right_to_work
    - public_meeting_places_in_local_development
  - the_vision_of_the_public_office:
    - the_public_office_in_practice
    - user_groups
    - ownership_forms_and_guidelines
    - forms_of_funding
    - form_and_content_of_the_activities
  - suggestions_for_forms_of_operation:
    - establishment_of_the_public_office_as_a_new_institution
    - use_of_temporarily_available_spaces
    - expansion_of_the_mandate_of_existing_institutions
  - the_public_office_as_a_political_issue:
    - labour
    - culture
    - business
    - education


# DICTIONARY
# ==========

index: Home
welcome: Welcome
support: Support
connect: Connect