safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    http://dilettant.se/thepublicoffice
# baseurl:    file:///Users/vectorsize/Dropbox/www/dilettant/thepublicoffice/_site
# url: http://dilettant.github.com/thepublicoffice

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

gravasize: 142

about:
  - team
  - project_phases:
    - phase_I
    - phase_II
  - philosophy:
    - open_source
    - cooperation
    - commons
    - diversity

concept:
  - summary
  - starting_points_and_perspectives:
    - changes_in_the_labour_market
    - public_meeting_places_and_the_right_to_work
    - public_meeting_places_in_local_development
  - the_vision_of_the_public_office:
    - the_public_office_in_practice
    - user_groups
    - ownership_forms_and_guidelines
    - forms_of_funding
    - form_and_content_of_the_activities
  - suggestions_for_forms_of_operation:
    - establishment_of_the_public_office_as_a_new_institution
    - use_of_temporarily_available_spaces
    - expansion_of_the_mandate_of_existing_institutions
  - the_public_office_as_a_political_issue:
    - labour
    - culture
    - business
    - education